CREATE DATABASE IF NOT EXISTS inforova CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE inforova;
CREATE TABLE admins(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,email VARCHAR(190) NOT NULL UNIQUE,password_hash VARCHAR(255) NOT NULL,status ENUM('active','blocked') NOT NULL DEFAULT 'active',created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE categories(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,name VARCHAR(120) NOT NULL,slug VARCHAR(140) NOT NULL UNIQUE,description VARCHAR(500) NOT NULL DEFAULT '',created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE articles(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,category_id BIGINT UNSIGNED NOT NULL,title VARCHAR(255) NOT NULL,slug VARCHAR(255) NOT NULL UNIQUE,excerpt VARCHAR(500) NOT NULL,content_html MEDIUMTEXT NOT NULL,status ENUM('draft','published') NOT NULL DEFAULT 'draft',published_at DATETIME NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,FOREIGN KEY(category_id) REFERENCES categories(id),KEY idx_articles_status_date(status,published_at),KEY idx_articles_category(category_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE pages(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,slug VARCHAR(140) NOT NULL UNIQUE,title VARCHAR(255) NOT NULL,meta_description VARCHAR(500) NOT NULL DEFAULT '',content_html MEDIUMTEXT NOT NULL,status ENUM('draft','published') NOT NULL DEFAULT 'published') ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE settings(setting_key VARCHAR(120) PRIMARY KEY,setting_value TEXT NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
INSERT INTO categories(name,slug,description) VALUES('Sarkari Job','sarkari-job','Government job updates, notices and application guides.'),('Exam News','exam-news','Important exam announcements, dates and results.'),('Exam Prep','exam-prep','Study resources, preparation tips and useful explainers.');
INSERT INTO settings VALUES('ad_top_code',''),('ad_inarticle_code',''),('ad_bottom_code',''),('bdxlink_return_url','https://bdxlink.xyz/continue.php');
INSERT INTO pages(slug,title,meta_description,content_html) VALUES
('about','About INFOROVA','About the INFOROVA publication','<h2>About us</h2><p>INFOROVA is an independent information website focused on useful, readable and organized content.</p><p>We aim to publish clear articles across jobs, exams and practical topics.</p>'),
('contact','Contact','Contact INFOROVA','<h2>Contact</h2><p>For editorial or website questions, contact the site administrator through the official contact channel published on this website.</p>'),
('privacy-policy','Privacy Policy','INFOROVA privacy policy','<h2>Privacy Policy</h2><p>We may process basic technical information such as browser, device and server logs to operate and secure the website. Advertising and analytics providers may use cookies or similar technologies according to their own policies.</p><p>Do not submit sensitive personal information through public forms.</p>'),
('terms','Terms of Use','Terms of use for INFOROVA','<h2>Terms of Use</h2><p>Content is provided for general informational purposes. Verify important dates, eligibility requirements and official notices with the relevant authority.</p>'),
('disclaimer','Disclaimer','INFOROVA disclaimer','<h2>Disclaimer</h2><p>INFOROVA is an independent publication and is not an official government authority unless explicitly stated. Information can change; readers should check primary sources before making decisions.</p>'),
('cookie-policy','Cookie Policy','INFOROVA cookie policy','<h2>Cookie Policy</h2><p>This site may use essential cookies for functionality and optional cookies from advertising or analytics services where configured.</p>');
INSERT INTO admins(email,password_hash) VALUES('admin@inforova.in','$2y$12$NzXYXVjeRHDo7D44leCrg.P4VojX7OvIYiEzAHaCxE/KCjHVAyEMq');
INSERT INTO articles(category_id,title,slug,excerpt,content_html,status,published_at) VALUES
(1,'How to Read a Government Job Notice Correctly','how-to-read-a-government-job-notice','A simple guide to checking eligibility, dates, documents and application instructions.','<p>Government job notices can contain many details. Start by checking the official notice date and application deadline.</p><h2>Check the essentials</h2><ul><li>Eligibility and age requirements</li><li>Application opening and closing dates</li><li>Required documents</li><li>Official application website</li></ul><p>Always verify the final information from the issuing authority.</p>','published',NOW()),
(2,'Exam News: What to Check Before Applying','exam-news-what-to-check-before-applying','Key items to verify before submitting an exam application.','<p>Before submitting an application, confirm the official notice, fee information, deadlines and required documents.</p><h2>Keep a checklist</h2><p>Save the official notice and record the important dates in your calendar.</p>','published',NOW()),
(3,'A Practical Weekly Exam Preparation Plan','practical-weekly-exam-preparation-plan','A flexible study structure for reviewing topics, practicing questions and tracking progress.','<p>A useful plan balances learning, practice and revision.</p><h2>Weekly structure</h2><p>Choose a small number of topics, practice questions regularly and reserve time to review mistakes.</p>','published',NOW());
