USE inforova;
INSERT IGNORE INTO categories(name,slug,description) VALUES
('Results','results','Exam results, merit lists and result-checking guides.'),
('Scholarships','scholarships','Scholarship information, application tips and education resources.'),
('Career Guide','career-guide','Practical career guidance, skills and application tips.');
INSERT IGNORE INTO pages(slug,title,meta_description,content_html) VALUES
('faq','FAQ','Frequently asked questions about INFOROVA','<h2>Frequently Asked Questions</h2><h3>Is INFOROVA an official government website?</h3><p>No. INFOROVA is an independent information website. Always verify important information with the official authority.</p><h3>How often is content updated?</h3><p>We update articles when new information is available and review important dates when possible.</p>'),
('editorial-policy','Editorial Policy','How INFOROVA publishes and reviews content','<h2>Editorial Policy</h2><p>We aim to publish clear, useful and responsibly sourced information. Where an article concerns an official process, readers are encouraged to verify the latest notice from the primary authority.</p>'),
('advertise','Advertise','Advertising information for INFOROVA','<h2>Advertising</h2><p>INFOROVA may display advertisements from third-party advertising partners. Ad placements are labeled and are intended to be separate from editorial content.</p>'),
('accessibility','Accessibility','INFOROVA accessibility statement','<h2>Accessibility</h2><p>We aim to keep pages readable on phones and desktops, use semantic headings and provide keyboard-friendly controls where practical.</p>');
INSERT IGNORE INTO articles(category_id,title,slug,excerpt,content_html,status,published_at) VALUES
((SELECT id FROM categories WHERE slug='sarkari-job'),'Government Job Application Checklist','government-job-application-checklist','A practical checklist for preparing a government job application.','<p>Before applying, collect the documents named in the official notice and confirm the deadline.</p><h2>Checklist</h2><ul><li>Read the complete official notice</li><li>Confirm eligibility</li><li>Prepare required documents</li><li>Review application details before submission</li></ul>','published',NOW()),
((SELECT id FROM categories WHERE slug='exam-news'),'Exam Date Update: How to Verify Official Notices','exam-date-update-how-to-verify-official-notices','How to confirm exam dates and avoid relying on outdated posts.','<p>Exam dates can change. Check the issuing authority website or official notice before making travel or study plans.</p><h2>Verify before sharing</h2><p>Look for the notice number, publication date and issuing authority.</p>','published',NOW()),
((SELECT id FROM categories WHERE slug='exam-prep'),'How to Make Better Revision Notes','how-to-make-better-revision-notes','Simple methods for organizing revision notes without making them unnecessarily long.','<p>Use headings, short definitions and practice questions. Review difficult topics more often than familiar ones.</p><h2>Keep notes useful</h2><p>Write notes that help you recall concepts rather than copying an entire textbook.</p>','published',NOW()),
((SELECT id FROM categories WHERE slug='results'),'How to Check an Exam Result Safely','how-to-check-an-exam-result-safely','A guide to finding the correct result page and avoiding unofficial links.','<p>Use the official result portal named in the examination notice. Check the web address before entering personal information.</p><h2>Protect your information</h2><p>Avoid entering passwords or sensitive information into unofficial result pages.</p>','published',NOW()),
((SELECT id FROM categories WHERE slug='scholarships'),'Scholarship Application Preparation Guide','scholarship-application-preparation-guide','What to prepare before completing a scholarship application.','<p>Read eligibility criteria carefully and prepare documents in advance.</p><h2>Before submission</h2><p>Review names, dates and uploaded documents. Save a copy of the final submission if the portal provides one.</p>','published',NOW()),
((SELECT id FROM categories WHERE slug='career-guide'),'Building a Simple Career Research Plan','building-a-simple-career-research-plan','A practical framework for comparing study and career options.','<p>Start with your interests and strengths, then compare education requirements, typical work and future learning opportunities.</p><h2>Compare options</h2><p>Use reliable sources and talk to trusted adults, teachers or qualified professionals when making important decisions.</p>','published',NOW());
